/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ats;

/**
 *
 * @author Mohit kumar
 */
import javax.swing.*;
import java.io.File;
import org.json.*;

public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    app frame;
    User user;

    public DashboardPanel(app frame, User user) {
        initComponents();
        this.frame = frame;
        this.user = user;

        if (!user.getRole().equals("admin")) {
            adminTab.setVisible(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminTab = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        adminTab.setBackground(new java.awt.Color(204, 204, 204));
        adminTab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adminTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ats/image/adminlogo.png"))); // NOI18N
        adminTab.setText("Admin Panel");
        adminTab.setIconTextGap(10);
        adminTab.addActionListener(this::adminTabActionPerformed);

        logout.setBackground(new java.awt.Color(153, 153, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(this::logoutActionPerformed);

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/ats/image/upload-svgrepo-com (1).png"))); // NOI18N
        jLabel2.setLabelFor(jButton1);
        jLabel2.setToolTipText("only pdf is accepted");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(0);
        jLabel2.setName(""); // NOI18N
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Upload your resume");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminTab, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
          JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File selectedFile = chooser.getSelectedFile();
            pdfParser p = new pdfParser();
            String parsedText = p.ParsePdf(selectedFile);
            if (parsedText.equals("Error")) {
                JOptionPane.showMessageDialog(
                        this,
                        "file is not selected properly or type is not pdf",
                        "Error",
                        JOptionPane.ERROR_MESSAGE

                );
            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "file is selected",
                        "sucess",
                        JOptionPane.INFORMATION_MESSAGE);

                revalidate();
                repaint();
                ApiCall a = new ApiCall();
                JSONObject atsData = a.getResponse(parsedText);
                if (atsData != null) {
                    frame.ShowSummary(atsData, user);
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "api call error ",
                            "Error",
                            JOptionPane.ERROR_MESSAGE

                    );

                }
            }
            // System.out.print(parsedText);

        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File selectedFile = chooser.getSelectedFile();
            pdfParser p = new pdfParser();
            String parsedText = p.ParsePdf(selectedFile);
            if (parsedText.equals("Error")) {
                JOptionPane.showMessageDialog(
                        this,
                        "file is not selected properly or type is not pdf",
                        "Error",
                        JOptionPane.ERROR_MESSAGE

                );
            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "file is selected",
                        "sucess",
                        JOptionPane.INFORMATION_MESSAGE);

                revalidate();
                repaint();
                ApiCall a = new ApiCall();
                JSONObject atsData = a.getResponse(parsedText);
                if (atsData != null) {
                    frame.ShowSummary(atsData, user);
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "api call error ",
                            "Error",
                            JOptionPane.ERROR_MESSAGE

                    );

                }
            }
            // System.out.print(parsedText);

        }
    }//GEN-LAST:event_jButton1ActionPerformed
// GEN-LAST:event_jButton1ActionPerformed

    private void adminTabActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminTabActionPerformed
        // TODO add your handling code here:
        frame.ShowAdminPanel(user);
    }// GEN-LAST:event_adminTabActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        frame.showLogin();
    }// GEN-LAST:event_logoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
